import { useEffect, useRef, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { useSubscription } from './useGymData';

export interface Banner {
  type: 'success' | 'error';
  text: string;
}

// Shared by PricingPage (first subscribe) and MyPage (re-pay/change cycle)
// -- both redirect through Toss's billing-auth (card registration) widget
// and land back here with ?billing=success&authKey=&customerKey=&plan=&cycle=
// (or ?billing=fail&code=&message=) on whichever `view` they came from.
export function useTossRedirect() {
  const { refreshGym } = useAuth();
  const { confirmPayment } = useSubscription();
  const [searchParams, setSearchParams] = useSearchParams();
  const [banner, setBanner] = useState<Banner | null>(null);
  // react-router hands back a new `searchParams` object identity on every
  // render, so this effect (deliberately dependent on it) can re-fire
  // mid-flight while confirmPayment is still pending, or again right after
  // it settles but before clearParams()'s setSearchParams has actually
  // removed billing=success from the URL -- a single resettable ref left a
  // race window right at that boundary (reset to null a tick before the URL
  // update commits) that still let a second confirm call through for the
  // same authKey, which Toss rejects as already-used. Tracking every
  // authKey ever started here (and never removing one) closes that window:
  // a fresh authKey is only ever generated by a new card-registration
  // attempt, so there's no legitimate case where the same one needs
  // reprocessing.
  const processedAuthKeysRef = useRef<Set<string>>(new Set());

  useEffect(() => {
    const billing = searchParams.get('billing');
    if (!billing) return;

    const clearParams = () => {
      const next = new URLSearchParams(searchParams);
      ['billing', 'authKey', 'customerKey', 'plan', 'cycle', 'code', 'message'].forEach((k) => next.delete(k));
      setSearchParams(next, { replace: true });
    };

    if (billing === 'fail') {
      const code = searchParams.get('code');
      const message = searchParams.get('message');
      setBanner({
        type: 'error',
        text: message
          ? `결제에 실패했어요: ${message}${code ? ` (${code})` : ''}`
          : '결제가 취소됐어요. 다시 시도해 주세요.',
      });
      clearParams();
      return;
    }

    if (billing === 'success') {
      const authKey = searchParams.get('authKey');
      const customerKey = searchParams.get('customerKey');
      const plan = searchParams.get('plan');
      const cycle = searchParams.get('cycle');
      if (!authKey || !customerKey || !plan || !cycle) {
        setBanner({ type: 'error', text: '결제 정보가 올바르지 않아요. 다시 시도해 주세요.' });
        clearParams();
        return;
      }
      if (processedAuthKeysRef.current.has(authKey)) return;
      processedAuthKeysRef.current.add(authKey);

      confirmPayment({
        authKey,
        customerKey,
        plan: plan as 'basic' | 'pro',
        billingCycle: cycle as 'monthly' | 'yearly',
      })
        .then(async () => {
          await refreshGym();
          setBanner({
            type: 'success',
            text: '결제가 완료됐어요! 플랜이 바로 적용되고, 다음 결제일에 등록하신 카드로 자동 갱신됩니다.',
          });
        })
        .catch((err) => {
          setBanner({ type: 'error', text: err instanceof Error ? err.message : '결제 처리 중 오류가 발생했어요.' });
        })
        .finally(() => {
          clearParams();
        });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [searchParams]);

  return { banner, setBanner };
}
